version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "nuget"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/Wabbajack.Web"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"