name: Blazor WASM Deployment
env:
  PUBLISH_DIR: Wabbajack.Web/bin/Release/net6.0/publish/wwwroot

on:
  push:
    branches: [redux]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Publish
        run: dotnet publish -c Release Wabbajack.Web/Wabbajack.Web.csproj --no-restore
        
      #- name: Rewrite base href
      #  uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      #  with:
      #    html_path: ${{ env.PUBLISH_DIR }}/index.html
      #    base_href: /BlazorOnGitHubPages/
      
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
