# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: code
  pull_request:
    branches: code
  schedule:
    - cron: "*/30 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: code
    - name: Use Node.js 14.1.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.1.x'
    - run: yarn install
    - run: yarn test
      env:
        CI: true

  deploy:
    needs: [test]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: code
    - name: Use Node.js 14.1.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.1.x'
    - run: yarn install
    - run: yarn build
      env:
        CI: false
    - name: Release GitHub Pages
      uses: igolopolosov/github-action-release-github-pages@v1
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        GITHUB_PAGES_REPO_AUTHOR: wabbajack-tools
        GITHUB_PAGES_REPO_NAME: wabbajack-tools.github.io
        GITHUB_PAGES_RELEASE_BRANCH: master
        PROJECT_BUILD_FOLDER: build
