name: Node.js CI

on:
  push:
    branches: code

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: code
    - name: Use Node.js 13.5.x
      uses: actions/setup-node@v1
      with:
        node-version: '13.5.x'
    - run: yarn install
    - run: yarn run deploy
      env:
        CI: true
